2020-03-16 14:45:17,760 - logs… - INFO - sql=INSERT INTO `t_host` (`host`, `port`, `explain`, `state`)
                VALUES ('http://49.235.241.182', '8089', 'testing', '1');
                
2020-03-16 14:45:17,891 - logs… - INFO - ()
2020-03-16 14:46:24,406 - logs… - INFO - sql=INSERT INTO `t_host` (`host`, `port`, `explain`, `state`)
                VALUES ('http://49.235.241.182', '8089', 'testing', '1');
                
2020-03-16 14:46:24,531 - logs… - INFO - ()
2020-03-16 14:46:37,444 - logs… - INFO - sql=INSERT INTO `t_host` (`host`, `port`, `explain`, `state`)
                VALUE ('http://49.235.241.182', '8089', 'testing', '1');
                
2020-03-16 14:46:37,563 - logs… - INFO - ()
2020-03-16 14:47:13,869 - logs… - INFO - sql=INSERT INTO `t_host` (`host`, `port`, `explain`, `state`)
                VALUE ('http://49.235.241.182', '8089', 'testing', '1');
                
2020-03-16 14:47:13,990 - logs… - INFO - ()
2020-03-16 14:48:20,034 - logs… - INFO - sql=INSERT INTO `t_host` (`host`, `port`, `explain`, `state`)
                VALUE ('http://49.235.241.182', '8089', 'testing', '1');
                
2020-03-16 14:48:20,234 - logs… - INFO - None
2020-03-16 14:49:33,718 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}]
2020-03-16 14:49:52,189 - logs… - INFO - [{'id': 2, 'test_code': '1', 'test_username': None, 'testcase_id': 1, 'testcase_result': 'test', 'testcase_recode': '200', 'testcase_count': 1, 'create_at': datetime.datetime(2020, 3, 12, 17, 25, 57), 'update_at': datetime.datetime(2020, 3, 12, 17, 26, 11), 'tc.id': 1, 'host_id': 1, 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None, 'tc.create_at': datetime.datetime(2020, 3, 12, 17, 27), 'tc.update_at': None}]
2020-03-16 14:53:57,694 - logs… - ERROR - error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': ' at line 2")
2020-03-16 14:54:10,694 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_testcase`(`host_id`, `url`, `requests_data`, `result`)
                VALUES ( 12, '/plantation/provincePlantationCounts', '', '{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}')
                
2020-03-16 14:54:10,828 - logs… - ERROR - error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': ' at line 2")
2020-03-16 14:54:53,492 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_testcase`(`host_id`, `url`, `requests_data`, `result`)
                VALUES ( 12, '/plantation/provincePlantationCounts', '', "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}")
                
2020-03-16 14:54:53,706 - logs… - INFO - None
2020-03-16 14:58:42,452 - logs… - INFO - sql=
                SELECT
                h.host,h.port,tc.url,tc.requests_data,tc.result
                FROM
                t_testcase tc
                LEFT JOIN t_host h on h.id = tc.host_id
                WHERE
                h.state = 1
                
2020-03-16 14:58:42,591 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://49.235.241.182', 'port': '8089', 'url': '/plantation/provincePlantationCounts', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-16 15:00:13,888 - logs… - INFO - sql=
                SELECT
                h.host,h.port,tc.url,tc.requests_data,tc.result
                FROM
                t_testcase tc
                LEFT JOIN t_host h on h.id = tc.host_id
                WHERE
                h.state = 1
                
2020-03-16 15:00:14,006 - logs… - ERROR - error: info() missing 1 required positional argument: 'msg'
2020-03-16 15:00:38,763 - logs… - INFO - sql=
                SELECT
                h.host,h.port,tc.url,tc.requests_data,tc.result
                FROM
                t_testcase tc
                LEFT JOIN t_host h on h.id = tc.host_id
                WHERE
                h.state = 1
                
2020-03-16 15:00:38,883 - logs… - INFO - <class 'list'>
2020-03-16 15:01:13,909 - logs… - INFO - sql=
                SELECT
                h.host,h.port,tc.url,tc.requests_data,tc.result
                FROM
                t_testcase tc
                LEFT JOIN t_host h on h.id = tc.host_id
                WHERE
                h.state = 1
                
2020-03-16 15:01:14,031 - logs… - INFO - {'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}
2020-03-16 15:01:14,031 - logs… - INFO - <class 'dict'>
2020-03-17 14:38:17,214 - logs… - INFO - sql=
                SELECT
                h.host,h.port,tc.url,tc.requests_data,tc.result
                FROM
                t_testcase tc
                LEFT JOIN t_host h on h.id = tc.host_id
                WHERE
                h.state = 1
                
2020-03-17 14:38:17,339 - logs… - INFO - {'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}
2020-03-17 14:38:17,339 - logs… - INFO - <class 'dict'>
2020-03-17 14:44:35,293 - logs… - ERROR - error: send_post() missing 1 required positional argument: 'data'
2020-03-17 14:45:52,280 - logs… - ERROR - error: HTTPConnectionPool(host='49.235.241.182', port=8089): Max retries exceeded with url: /plantation/provincePlantationCounts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002129A31D7B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-03-17 14:47:04,885 - logs… - ERROR - error: HTTPConnectionPool(host='49.235.241.182', port=8089): Max retries exceeded with url: /plantation/provincePlantationCounts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CEEA5DD710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-03-17 14:47:39,522 - logs… - ERROR - error: HTTPConnectionPool(host='49.235.241.182', port=8089): Max retries exceeded with url: /plantation/provincePlantationCounts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9BDBCB7F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-03-17 14:48:25,117 - logs… - ERROR - error: HTTPConnectionPool(host='49.235.241.182', port=8089): Max retries exceeded with url: /plantation/provincePlantationCounts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B05DF1D7B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-03-17 14:49:21,888 - logs… - ERROR - error: HTTPConnectionPool(host='49.235.241.182', port=8089): Max retries exceeded with url: /plantation/provincePlantationCounts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F656E7D7B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-03-17 14:54:22,773 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:00:02,522 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:08:00,513 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:18:03,251 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:18:17,621 - logs… - ERROR - error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': ' at line 2")
2020-03-17 15:18:17,754 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:18:17,895 - logs… - ERROR - error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'p' at line 2")
2020-03-17 15:19:11,911 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171519113362', 'testname', 1, '{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}', '200', 1)
                
2020-03-17 15:19:12,040 - logs… - ERROR - error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': ' at line 2")
2020-03-17 15:19:12,172 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:19:12,173 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171519126283', 'testname', 2, '{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]}', '200', 1)
                
2020-03-17 15:19:12,303 - logs… - ERROR - error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'p' at line 2")
2020-03-17 15:20:19,240 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171520196197', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 15:20:19,551 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:20:19,552 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171520197747', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]}", '200', 1)
                
2020-03-17 15:20:19,672 - logs… - ERROR - error: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'{\'year\': \'2019\'}", \'result\': None}, {\'host\': \'http://127.0.0.1\', \'port\': \'8089\',\' at line 2')
2020-03-17 15:25:38,187 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171525387375', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 15:25:38,516 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:25:38,517 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171525384842', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]}", '200', 1)
                
2020-03-17 15:25:39,025 - logs… - ERROR - error: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'{\'year\': \'2019\'}", \'result\': None}, {\'host\': \'http://127.0.0.1\', \'port\': \'8089\',\' at line 2')
2020-03-17 15:41:24,580 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171541243823', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 15:41:24,917 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:41:24,919 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171541244674', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': '{'year': '2019'}', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': '{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}'}]}", '200', 1)
                
2020-03-17 15:41:25,050 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-17 15:43:10,937 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171543107439', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 15:43:11,425 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 15:43:11,427 - logs… - ERROR - error: invalid syntax (<unknown>, line 1)
2020-03-17 16:09:39,740 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171609396838', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:09:40,069 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:09:40,071 - logs… - ERROR - error: unexpected character after line continuation character (<unknown>, line 1)
2020-03-17 16:10:38,344 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171610380628', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:10:38,651 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:10:38,653 - logs… - ERROR - error: unexpected character after line continuation character (<unknown>, line 1)
2020-03-17 16:20:44,564 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171620448296', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:20:44,886 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:20:44,887 - logs… - ERROR - error: unexpected character after line continuation character (<unknown>, line 1)
2020-03-17 16:23:48,720 - logs… - ERROR - error: sequence item 0: expected str instance, dict found
2020-03-17 16:25:04,454 - logs… - ERROR - error: 'dict' object has no attribute 'translate'
2020-03-17 16:26:41,593 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171626412473', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:26:41,955 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:26:41,956 - logs… - ERROR - error: invalid syntax (<unknown>, line 1)
2020-03-17 16:29:44,432 - logs… - ERROR - error: name 'ret' is not defined
2020-03-17 16:30:03,868 - logs… - ERROR - error: unexpected character after line continuation character (<unknown>, line 1)
2020-03-17 16:31:31,149 - logs… - ERROR - error: unexpected character after line continuation character (<unknown>, line 1)
2020-03-17 16:31:57,997 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171631571352', 'testname', 1, "{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'m01\': 13.24, \'m02\': 18.31, \'m03\': 18.87, \'m04\': 24.88, \'m05\': 21.03, \'m06\': 9.05, \'m07\': 5.07, \'m08\': 9.72, \'m09\': 1.88, \'m10\': -0.47, \'m11\': 0.93, \'m12\': 6.31}]}", '200', 1)
                
2020-03-17 16:31:58,351 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:31:58,352 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171631582139', 'testname', 2, "{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'host\': \'http://49.235.241.182\', \'port\': \'8080\', \'url\': \'/price/monCorrespondingPeriod\', \'requests_data\': "{\'year\': \'2019\'}", \'result\': None}, {\'host\': \'http://127.0.0.1\', \'port\': \'8089\', \'url\': \'/testing/showTestCase\', \'requests_data\': \'\', \'result\': "{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'province\': \'山东省\', \'counts\': 918}"}]}", '200', 1)
                
2020-03-17 16:31:58,485 - logs… - ERROR - error: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'{\\\'year\\\': \\\'2019\\\'}", \\\'result\\\': None}, {\\\'host\\\': \\\'http://127.0.0.1\\\', \\\'por\' at line 2')
2020-03-17 16:32:52,454 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171632523798', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:32:52,787 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:32:52,789 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171632524409', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]}", '200', 1)
                
2020-03-17 16:32:52,923 - logs… - ERROR - error: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'{\'year\': \'2019\'}", \'result\': None}, {\'host\': \'http://127.0.0.1\', \'port\': \'8089\',\' at line 2')
2020-03-17 16:33:16,852 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171633169408', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:33:17,165 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:33:17,166 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171633170626', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': '{'year': '2019'}', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': '{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}'}]}", '200', 1)
                
2020-03-17 16:33:17,282 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-17 16:33:41,102 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171633419184', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:33:41,409 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:33:41,410 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171633410573', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': \'{'year': '2019'}\', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': \'{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}\'}]}", '200', 1)
                
2020-03-17 16:33:41,529 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-17 16:34:02,785 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171634025099', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:34:03,090 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:34:03,091 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171634032406', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': \'{'year': '2019'}\', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': \'{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}\'}]}", '200', 1)
                
2020-03-17 16:34:03,207 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-17 16:34:48,688 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171634483392', 'testname', 1, "{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'m01\': 13.24, \'m02\': 18.31, \'m03\': 18.87, \'m04\': 24.88, \'m05\': 21.03, \'m06\': 9.05, \'m07\': 5.07, \'m08\': 9.72, \'m09\': 1.88, \'m10\': -0.47, \'m11\': 0.93, \'m12\': 6.31}]}", '200', 1)
                
2020-03-17 16:34:48,999 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:34:49,001 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171634494594', 'testname', 2, "{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'host\': \'http://49.235.241.182\', \'port\': \'8080\', \'url\': \'/price/monCorrespondingPeriod\', \'requests_data\': \\'{\'year\': \'2019\'}\\', \'result\': None}, {\'host\': \'http://127.0.0.1\', \'port\': \'8089\', \'url\': \'/testing/showTestCase\', \'requests_data\': \'\', \'result\': \\'{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'province\': \'山东省\', \'counts\': 918}\\'}]}", '200', 1)
                
2020-03-17 16:34:49,117 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-17 16:35:18,162 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171635182661', 'testname', 1, "{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'m01\': 13.24, \'m02\': 18.31, \'m03\': 18.87, \'m04\': 24.88, \'m05\': 21.03, \'m06\': 9.05, \'m07\': 5.07, \'m08\': 9.72, \'m09\': 1.88, \'m10\': -0.47, \'m11\': 0.93, \'m12\': 6.31}]}", '200', 1)
                
2020-03-17 16:35:18,500 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:35:18,501 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171635187107', 'testname', 2, "{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'host\': \'http://49.235.241.182\', \'port\': \'8080\', \'url\': \'/price/monCorrespondingPeriod\', \'requests_data\': \'{\'year\': \'2019\'}\', \'result\': None}, {\'host\': \'http://127.0.0.1\', \'port\': \'8089\', \'url\': \'/testing/showTestCase\', \'requests_data\': \'\', \'result\': \'{\'errcode\': \'0\', \'errmsg\': \'成功\', \'data\': [{\'province\': \'山东省\', \'counts\': 918}\'}]}", '200', 1)
                
2020-03-17 16:35:18,631 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-17 16:36:12,005 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171636126288', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:36:12,346 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:36:12,348 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171636128667', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': '{'year': '2019'}', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': '{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}'}]}", '200', 1)
                
2020-03-17 16:36:12,479 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-17 16:36:19,615 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171636193023', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-17 16:36:19,979 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-17 16:36:19,980 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003171636192783', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': '{'year': '2019'}', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': '{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}'}]}", '200', 1)
                
2020-03-17 16:36:20,112 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-18 08:43:18,948 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003180843184963', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-18 08:43:19,274 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-18 08:43:19,275 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003180843196124', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': '{'year': '2019'}', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': '{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}'}]}", '200', 1)
                
2020-03-18 08:43:19,391 - logs… - ERROR - error: (1406, "Data too long for column 'testcase_result' at row 1")
2020-03-18 08:47:51,051 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003180847514948', 'testname', 1, "{'errcode': '0', 'errmsg': '成功', 'data': [{'m01': 13.24, 'm02': 18.31, 'm03': 18.87, 'm04': 24.88, 'm05': 21.03, 'm06': 9.05, 'm07': 5.07, 'm08': 9.72, 'm09': 1.88, 'm10': -0.47, 'm11': 0.93, 'm12': 6.31}]}", '200', 1)
                
2020-03-18 08:47:51,376 - logs… - INFO - [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': "{'year': '2019'}", 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': "{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}"}]
2020-03-18 08:47:51,378 - logs… - INFO - sql=
                INSERT INTO `apitesting`.`t_test_log`(`test_code`, `test_username`, `testcase_id`, `testcase_result`, `testcase_recode`, `testcase_count`)
                VALUES ('202003180847516118', 'testname', 2, "{'errcode': '0', 'errmsg': '成功', 'data': [{'host': 'http://49.235.241.182', 'port': '8080', 'url': '/price/monCorrespondingPeriod', 'requests_data': '{'year': '2019'}', 'result': None}, {'host': 'http://127.0.0.1', 'port': '8089', 'url': '/testing/showTestCase', 'requests_data': '', 'result': '{'errcode': '0', 'errmsg': '成功', 'data': [{'province': '山东省', 'counts': 918}'}]}", '200', 1)
                
